dist: trusty
sudo: false

language: php
php:
- '7.0'
- '7.1'

env: NODE_ENV="test"
notifications:
  email: false

install:
- nvm install 8
- nvm use 8
- npm install

script: npm test
after_success: npm run coverage
