dist: xenial
env: [NODEJS=10, NODEJS=11]
language: php
notifications: {email: false}
php: ['7.2', '7.3']

before_install: nvm install ${NODEJS}
install: npm install
script: npm test
after_success: npm run coverage
