dist: trusty
language: php
sudo: false

env: NODE_ENV="test"
php: '7.1'
notifications:
  email: false

install:
- nvm install 8
- nvm use 8
- npm install

script: npm test
after_success: npm run coverage
